lib/resolver-factory.ts

fix: return id on create

---

e2e/simple-crud.spec.ts
lib/resolver-factory.ts
package.json

fix: returns id on get one and e2e

---

e2e/embedded.spec.ts
e2e/example.spec.ts
e2e/references-many.spec.ts
e2e/simple-crud.spec.ts
lib/property.ts
lib/resolver-factory.ts

test: add more coverage

---

README.md
lib/property.ts

docs: add discord and remove graphql

---

e2e/embedded.spec.ts
e2e/references-many.spec.ts
e2e/simple-crud.spec.ts
lib/entity.ts
lib/resolver-factory.ts
lib/typer.ts
src/models/author.ts
src/models/product.ts
src/resolvers/auth.resolver.ts

feat: separate input for create and update

---

e2e/embedded.spec.ts
lib/property.ts
lib/resolver-factory.ts
lib/typer.ts
lib/util.ts
src/models/author.ts
src/models/product.ts

fix: unable to returns ids

---

e2e/simple-crud.spec.ts
lib/resolver-factory.ts
lib/types.ts
src/resolvers/auth.resolver.ts

feat: basic remove api

---

e2e/embedded.spec.ts
lib/resolvers/embedded.resolver.ts

Resolve #53 
Issue Number: 53
Remove the embedded data in a model.

feat: remove embedded

---

CONTRIBUTING.md

docs :Update CONTRIBUTING.md

---

e2e/embedded.spec.ts
lib/resolvers/embedded.resolver.ts
package-lock.json

feat: get all API for embedded

---

README.md

docs: Add discord and Paypal

---

.github/workflows/ci.yml
.prettierrc
README.md
e2e/embedded.spec.ts
e2e/simple-crud.spec.ts
e2e/test-server.ts
lib/js/pluralize.js
lib/module.ts
lib/property.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/resolvers/references-many.resolver.ts
lib/resolvers/shared.ts
lib/typer.ts
lib/util.ts
src/models/product.ts
src/resolvers/auth.resolver.ts

refactor: Change code width

---

e2e/simple-crud.spec.ts
lib/resolvers/crud.resolver.ts

feat: implement update api

---

.eslintignore

ESLint was configured to run on `<tsconfigRootDir>/.eslintrc.js` using `parserOptions.project`

fix: fix Parsing error in Eslint

---

lib/inspect.ts
lib/metadata.ts
lib/module.ts
lib/property.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/resolvers/references-many.resolver.ts
lib/resolvers/shared.ts
lib/typer.ts
src/models/product.ts

refactor: part 2

---

e2e/auth.spec.ts
src/models/user.ts
src/resolvers/auth.resolver.ts

test: add e2e for auth resolver

---

lib/metadata.ts
lib/property.ts
src/models/user.ts

test: fix fail coverage ci 

---

e2e/simple-crud.spec.ts
e2e/test-server.ts
lib/entity.ts
lib/js/mongoose-paginate-v2/README.md
lib/js/mongoose-paginate-v2/index.d.ts
lib/js/mongoose-paginate-v2/index.js
lib/js/mongoose-paginate-v2/pagination-parameters.js
lib/js/mongoose-paginate-v2/pagination-subdocs.js
lib/module.ts
lib/resolvers/crud.resolver.ts
lib/typer.ts

feat: paginate part 1

---

e2e/test-server.ts

https://github.com/nestjs/graphql/issues/2060
Issue Number: #83 
Remove logging errors when the test case passes

ci: remove test pass error logs

---

lib/resolvers/crud.resolver.ts

fix: References many from in curd resolver

---

lib/entity.ts
lib/metadata.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/resolvers/references-many.resolver.ts
lib/resolvers/shared.ts
lib/typer.ts
src/models/author.ts
src/models/product.ts
src/resolvers/auth.resolver.ts

refactor: typer

---

lib/entity.ts
lib/index.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/resolvers/references-many.resolver.ts
lib/resolvers/shared.ts
lib/type-functions.ts
src/models/author.ts
src/models/product.ts
src/resolvers/auth.resolver.ts

refactor: typer signature

---

lib/entity.ts
lib/inspect.spec.ts
lib/inspect.ts
lib/metadata.ts
lib/resolvers/crud.resolver.ts
lib/shared.ts
src/models/author.ts
src/models/product.ts
src/models/user.ts

feat: pick api per entity

---

lib/js/graphql-json-type.js
package-lock.json

feat: add json type

---

e2e/paginate.spec.ts
lib/resolvers/crud.resolver.ts
lib/type-functions.ts

feat: simple paginate api

---

e2e/test-server.ts
lib/module.ts
src/app.module.ts

fix: remove monkey patch for this.model.paginate

---

e2e/bulk.spec.ts
lib/definition.ts
lib/resolvers/crud.resolver.ts
lib/type-functions.ts

- [] Code style update (formatting, local variables)
Issue Number: #98 
add bulkDeleteTags

feat: bulk delete

---

e2e/bulk.spec.ts
lib/definition.ts
lib/module.ts
lib/resolvers/crud.resolver.ts
lib/type-functions.ts

refactor: Change name from delete to remove

---

lib/inspect.ts
lib/metadata.ts
lib/property.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/resolvers/references-many.resolver.ts

refactor: Stronger type for references many

---

lib/definition.ts
lib/metadata.ts
lib/property.ts
lib/resolvers/crud.resolver.ts
lib/type-functions.ts
src/models/user.ts

feat: filterable

---

e2e/paginate.spec.ts
lib/mongo-helper.spec.ts
lib/mongo-helper.ts
lib/resolvers/crud.resolver.ts
lib/type-functions.ts
src/models/customer.ts
src/models/index.ts

Issue Number: #113 
add filter for paginate

feat: paginate with filter

---

CONTRIBUTING.md
package-lock.json
package.json

docs: update small things with package.json

---

lib/context.ts
lib/resolvers/crud.resolver.ts
lib/type-functions/base.ts

feat: Add context into base service

---

lib/base.service.ts
lib/resolvers/crud.resolver.ts

refactor: Move all functions in crud resolver to base service provider

---

e2e/bulk.spec.ts
e2e/test-server.ts
lib/resolvers/crud.resolver.ts
src/models/product.ts

feat: add array validation for bulk

---

lib/base.service.ts
lib/context.ts
lib/module.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/resolvers/references-many.resolver.ts

feat: Add context decorator

---

cspell.json
e2e/object-embedded.e2e.spec.ts

test: create a test for embedded object

---

e2e/paginate.spec.ts
e2e/simple-crud.spec.ts
lib/base.service.ts
lib/resolvers/crud.resolver.ts
lib/util.ts
src/models/author.ts
src/models/product.ts
src/models/user.ts
src/models/variant.ts

feat: apply sortable and filter into getAll

---

src/models/author.ts
src/models/product.ts
src/models/user.ts
src/models/variant.ts

chore: revert unneeded changes

---

README.md
e2e/auth.spec.ts
e2e/embedded-allow-apis.spec.ts
e2e/embedded.spec.ts
e2e/paginate.spec.ts
e2e/simple-crud.spec.ts
e2e/test-server.ts
lib/base.service.ts
lib/hook.ts
lib/index.ts
lib/inspect.spec.ts
lib/inspect.ts
lib/metadata.ts
lib/module.ts
lib/property.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/shared.ts
src/app.module.ts
src/ctx.ts
src/models/author.ts
src/models/user.ts
src/resolvers/auth.resolver.ts

feat: context decorator with hooks

---

e2e/object-embedded.spec.ts
lib/module.ts
lib/resolvers/shared.ts
src/app.module.ts
src/models/computer.ts
src/models/index.ts

refactor: clean up for embedded

---

e2e/simple-crud.spec.ts
lib/base.service.ts
lib/hook.ts

feat: general hook

---

README.md

chore: Update discord url

---

e2e/object-embedded.spec.ts
src/models/computer.ts

test: e2e three layer object embedded

---

lib/base.service.ts
lib/resolvers/crud.resolver.ts

feat: make relations recursive

---

e2e/bulk.spec.ts
e2e/example.spec.ts
e2e/has-many.spec.ts
e2e/has-one.spec.ts
e2e/references-many.spec.ts
e2e/simple-crud.spec.ts
src/app.module.ts
src/models/product.ts

test: e2e three layers references many

---

e2e/embedded.spec.ts
src/models/author.ts

test: three layers embedded array

---

e2e/simple-crud.spec.ts
lib/base.service.ts

test: more e2e for hooks

---

e2e/example.spec.ts
e2e/has-many.spec.ts
e2e/has-one.spec.ts
e2e/references-many.spec.ts
src/app.module.ts
src/models/variant.ts

test: e2e for three layer HasMany

---

e2e/object-embedded.spec.ts
lib/property.ts
src/models/author.ts
src/models/computer.ts
src/models/product.ts

feat: enhance embedded decorator

---

README.md
e2e/bulk.spec.ts
e2e/embedded-allow-apis.spec.ts
e2e/embedded.spec.ts
e2e/simple-crud.spec.ts
jest-e2e.json
jest-unit.json
lib/base.service.ts
lib/object-id.ts
lib/property.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/shared.ts
lib/type-functions/bulk-remove-output-type.ts
src/models/author.ts
src/models/computer.ts
src/models/customer.ts
src/models/product.ts
src/models/user.ts
src/models/variant.ts

feat: graphql object id

---

README.md

docs: Update usage and remove dep

---

e2e/embedded-allow-apis.spec.ts
e2e/simple-crud.spec.ts
e2e/test-server.ts
lib/module.ts
lib/property.ts

feat: mongoose schema customizable

---

lib/metadata.ts
lib/property.ts

refactor: remove excluded on database

---

e2e/has-one.spec.ts
lib/inspect.ts
lib/metadata.ts
lib/module.ts
lib/object-id.ts
lib/property.ts
lib/resolvers/belongs-to.resolver.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/resolvers/index.ts
lib/shared.ts
src/models/product.ts

feat: belongs to

---

e2e/has-many.spec.ts
lib/resolvers/belongs-to.resolver.ts
lib/resolvers/has-many.resolver.ts
lib/resolvers/has-one.resolver.ts
lib/resolvers/references-many.resolver.ts

feat: increase loader performance

---

lib/property.ts
lib/resolvers/references-many.resolver.ts
src/models/product.ts

feat: Add allowCreateWithin and noPopulation

---

lib/definition.ts
lib/type-functions/base.ts
lib/type-functions/create-input-type.ts
lib/type-functions/output-type.ts
lib/type-functions/update-input-type.ts

feat: Stronger type for some base types

---

e2e/paginate.spec.ts
src/models/customer.ts
src/models/product.ts

Resolves #184 
Issue Number: #184

test: filter object id on paginate

---

e2e/example.spec.ts
e2e/has-many.spec.ts
e2e/has-one.spec.ts
e2e/references-many.spec.ts
lib/property.ts
lib/resolvers/belongs-to.resolver.ts
lib/resolvers/has-many.resolver.ts
lib/resolvers/has-one.resolver.ts
lib/resolvers/references-many.resolver.ts
src/app.module.ts
src/models/product.ts

feat: paginated on has many

---

e2e/belongs-to.spec.ts
e2e/simple-crud.spec.ts
lib/base.service.ts
lib/default.hook.ts
lib/hook.ts
lib/inspect.ts
lib/module.ts
lib/property.ts

feat: init default hook

---

e2e/auth.spec.ts
e2e/test-server.ts
lib/definition.ts
lib/metadata.ts
lib/resolvers/crud.resolver.ts
lib/util.spec.ts
lib/util.ts
src/models/user.ts

feat: auth for resolvers

---

e2e/embedded.spec.ts
lib/property.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/resolvers/shared.ts
src/models/author.ts
src/models/fake-guards.ts
src/models/user.ts

feat: auth for embedded

---

e2e/example.spec.ts
e2e/test-server.ts
lib/index.ts
lib/metadata.ts
lib/module.ts
lib/mongoose-index-decorator.ts
src/models/user.ts

feat: add Index decorator

---

e2e/paginate.spec.ts
lib/definition.ts
lib/mongo-helper.ts
lib/resolvers/crud.resolver.ts
lib/type-functions/filter-type.ts
lib/util.ts
src/models/customer.ts
src/models/user.ts

feat: support mongo text search

---

e2e/references-many.spec.ts
lib/default.hook.ts
lib/hook.ts
lib/index.ts
lib/module-options.ts
lib/module.ts

feat: get related references many

---

lib/base.service.ts
lib/default.hook.ts

fix: revisit util.memoize inside classes

---

e2e/bulk.spec.ts
e2e/has-many.spec.ts
e2e/has-one.spec.ts
e2e/references-many.spec.ts
lib/default.hook.ts
src/models/product.ts

Resolves: #174 
Issue Number: #174

feat: default hooks for relations

---

e2e/has-many.spec.ts
e2e/remove-options.spec.ts
e2e/simple-crud.spec.ts
e2e/test-server.ts
lib/base.service.ts
lib/default.hook.spec.ts
lib/default.hook.ts
lib/definition.ts
lib/hook.ts
lib/module-options.ts
lib/module.ts
lib/remove-options.ts
lib/resolvers/crud.resolver.ts
src/models/product.ts

feat: remove options

---

e2e/references-many.spec.ts
lib/base.service.ts
lib/default.hook.ts
lib/resolvers/embedded.resolver.ts
src/resolvers/auth.resolver.ts

Resolves: #223 
Issue Number: #223

feat:add referenceMany for beforeCreate/beforeUpdate and e2e test

---

lib/default.hook.ts
lib/definition.ts
lib/relations/belongs-to.ts
lib/relations/has-many.ts
lib/relations/has-one.ts
lib/relations/references-many.ts

feat: skip default hooks for relations

---

lib/bulk-error-handler.ts
lib/index.ts
lib/resolvers/crud.resolver.ts

feat: Add bulk error handler

---

e2e/remove-options.spec.ts
lib/default.hook.ts
src/models/product.ts

fix: missing handler for ref many

---

README.md
a.sh
e2e/paginate.spec.ts
lib/default.hook.ts
lib/hook.ts

chore: export hook types

---

README.md

docs: missing install step

---

lib/base.service.ts
lib/relations/embedded.ts
lib/resolvers/embedded.resolver.ts
lib/type-functions/paginate-output-type.ts

fix: serveral small fixes

---

e2e/embedded.spec.ts
lib/resolvers/belongs-to.resolver.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/resolvers/has-many.resolver.ts
lib/resolvers/has-one.resolver.ts
lib/resolvers/references-many.resolver.ts
src/models/product.ts

feat: transform when response

---

e2e/embedded.spec.ts
lib/property.ts
lib/relations/embedded.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
src/models/author.ts

feat: override embedded

---

cspell.json

fix: cspell ignore

---

lib/index.ts

fix: missing export for default hook

---

lib/index.ts

fix: adding export for base service

---

package.json

fix: repo field

---

e2e/object-embedded.spec.ts

test: check remove and update embedded work

---

e2e/embedded.spec.ts
e2e/object-embedded.spec.ts
src/models/author.ts

- Rename Book.name -> Book.title
- Review.name -> Review.content

test: Rename properties in author.ts for less confusion

---

e2e/embedded.spec.ts

fix: typo on test cause drop on coverage

---

lib/definition.ts

fix: schema customizable

---

e2e/object-embedded.spec.ts
e2e/skip-hooks.spec.ts
lib/default.hook.ts
src/app.module.ts
src/models/computer.ts
src/models/index.ts
src/models/order.ts

test: add e2e skip hooks default

---

.github/workflows/ci.yml
.husky/pre-push
README.md
a.sh

chore: make getting started simpler

---

.github/workflows/ci.yml
lib/definition.ts

fix: Add timestamp to definition

---

e2e/simple-crud.spec.ts
lib/base.service.spec.ts
lib/base.service.ts
lib/hook.ts

feat: should apply for context and more hooks

---

lib/base.service.ts

fix: exclude beforeReadFilter for write

---

README.md
e2e/embedded-allow-apis.spec.ts
lib/inspect.ts
lib/relations/embedded.ts
lib/resolvers/embedded.resolver.ts
src/models/author.ts

fix: default value for allow apis

---

lib/base.service.ts
lib/hook.ts

fix: change shouldApplyForContext signature

---

e2e/embedded.spec.ts

test: add test on verify update remove embedded result

---

e2e/check-id-type.spec.ts
lib/base.service.ts
lib/property.ts

fix: throw error when define id with string

---

lib/resolvers/embedded.resolver.ts

fix: id errors on embedded

---

lib/resolvers/has-many.resolver.ts
lib/resolvers/has-one.resolver.ts
lib/type-functions/base.ts
src/main.ts

Resolves: #247
Resolves: #271 

refactor: Transform cause _id mess up

---

e2e/object-embedded.spec.ts
e2e/skip-hooks.spec.ts
src/app.module.ts
src/models/author.ts
src/models/computer.ts

refactor: rename some collections

---

.github/workflows/deploy.yml

ci: Add deploy yaml

---

e2e/embedded.spec.ts

test: update deep embedded

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
src/app.module.ts
src/main.ts
src/models/author.ts

ci: deploy to gcp cloud run

---

e2e/embedded.spec.ts

refactor: update some small test case

---

src/main.ts

chore: add x-dryerjs-api-key for dev env

---

e2e/multiple-relations.spec.ts
lib/resolvers/belongs-to.resolver.ts
lib/resolvers/has-many.resolver.ts
lib/resolvers/has-one.resolver.ts
lib/resolvers/references-many.resolver.ts

fix: bug when has multiple belongs to

---

lib/inspect.spec.ts

test: Increase inspect test coverage

---

e2e/simple-crud.spec.ts
lib/base.service.ts
lib/resolvers/embedded.resolver.ts

feat: find one without throwing

---

lib/relations/has-one.ts
lib/resolvers/has-one.resolver.ts

fix: has one should be nullable

---

cspell.json
e2e/base-model.spec.ts
lib/type-functions/base.ts

fix: base class issue

---

e2e/base-model.spec.ts
lib/type-functions/base.ts

test: use base model inside a function

---

e2e/simple-crud.spec.ts
lib/base.service.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
lib/type-functions/base.ts

fix: remove logs and new methods

---

lib/module.ts

fix: missing export for DRYER_MODULE_OPTIONS

---

lib/module.ts

fix: id as object id

---

lib/relations/embedded.ts
src/models/computer.ts

fix: convert id on sub schema

---

lib/base.service.ts

feat: expose model from base service

---

e2e/test-server.ts
lib/base.service.ts
lib/default.hook.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
src/resolvers/auth.resolver.ts

fix: using nest common errors

---

lib/module.ts

fix: export hooks

---

lib/module-options.ts
lib/module.ts

feat: ability to add providers and imports

---

tsconfig.json

fix: build with comments to show deprecated

---

e2e/bulk.spec.ts
e2e/embedded-allow-apis.spec.ts
e2e/example.spec.ts
e2e/has-many.spec.ts
e2e/multiple-relations.spec.ts
e2e/object-embedded.spec.ts
e2e/paginate.spec.ts
e2e/remove-options.spec.ts
e2e/simple-crud.spec.ts
lib/definition.ts
lib/module-options.ts
lib/relations/embedded.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/embedded.resolver.ts
src/app.module.ts
src/models/author.ts
src/models/computer.ts
src/models/customer.ts
src/models/order.ts
src/models/product.ts

feat: remove deprecated features

---

e2e/auth.spec.ts
e2e/bulk.spec.ts
e2e/embedded-allow-apis.spec.ts
e2e/embedded.spec.ts
e2e/example.spec.ts
e2e/has-many.spec.ts
e2e/multiple-relations.spec.ts
e2e/object-embedded.spec.ts
e2e/paginate.spec.ts
e2e/remove-options.spec.ts
e2e/simple-crud.spec.ts
e2e/test-server.ts
lib/default.hook.ts
lib/definition.ts
lib/module-options.ts
lib/module.ts
lib/relations/has-many.ts
lib/relations/has-one.ts
lib/resolvers/crud.resolver.ts
src/app.module.ts

feat: move all resolver configs into definitions

---

lib/base.service.ts
lib/module.ts

feat: accept def as name string

---

lib/module.ts

fix: id should be object id

---

lib/base.service.ts

fix: incorrect hook order

---

lib/definition.ts
lib/property.ts
lib/relations/embedded.ts
lib/thunk.ts
lib/type-functions/base.ts
lib/type-functions/index.ts
lib/type-functions/update-embedded-input-type.ts

fix: update input id should be required

---

lib/resolvers/crud.resolver.ts

fix: findOne query name

---

lib/mongo-helper.ts

fix: issue with has own property

---

lib/type-functions/filter-type.ts

fix: prevent duplicated input filter type name

---

e2e/simple-crud.spec.ts
lib/resolvers/belongs-to.resolver.ts
lib/resolvers/crud.resolver.ts
lib/resolvers/has-many.resolver.ts
lib/resolvers/has-one.resolver.ts
lib/resolvers/references-many.resolver.ts
lib/shared.spec.ts
lib/shared.ts

feat: add QueryContext

---

e2e/bulk.spec.ts
lib/base.service.ts

fix: typeFunc should work as an array as well

---

lib/index.ts

fix: export graphql-type-json

---

e2e/has-many.spec.ts
e2e/has-one.spec.ts
e2e/multiple-relations.spec.ts
lib/relations/has-many.ts
lib/relations/has-one.ts
src/models/product.ts

fix: missing transform inside create within

---

e2e/multiple-relations.spec.ts
lib/relations/has-many.ts
lib/relations/has-one.ts

fix: circular issue

---

lib/base.service.ts

fix: add options for update

---

e2e/belongs-to.spec.ts
lib/base.service.ts
lib/resolvers/belongs-to.resolver.ts
lib/resolvers/has-many.resolver.ts
lib/resolvers/has-one.resolver.ts
lib/resolvers/references-many.resolver.ts

feat: shared loader
